### ISSUE TITLE
Issue with $this->request->is('post')

### ISSUE THREAD

**Issue by highstrike** [ADmad/CakePHP-HybridAuth#8]
Hi,

I've tried your plugin and i've setup my facebook application but I have to press the button twice in order to login.

I've narrowed it down to `if ($this->request->is('post')) {` in the controller login function. This returns false when you first submit this form.

```
    <?php
        echo $this->Form->create('User');
        echo $this->Form->input('provider', array('value' => 'Facebook'));
        echo $this->Form->end('Submit');
    ?>
```

Apparently the first time you click to login with facebook, the plugin via the library communicates well with facebook servers but then it won't go straight into `$this->Auth->login()` (to actually log you in the first time) because when it comes back from facebook through the endpoint it's not a post anymore and that's why when you press the button to login with facebook a second time, it will work because it already has the facebook stuff stored in session and then its actually a post.

I haven't tried other services yet.
Thanks.

**Later EDIT**
Twitter behaves the same way, having to submit the form twice because it stops at the same if condition, the request that comes back from twitter is not post so it doesn't go into `$this->Auth->login()`

**Comment by chrisvogt** [comment]
I am having the same issue. I'll let you know if I uncover anything. Perhaps it'll be apparent to you or you'll have ideas to suggest.

`redirectUrl()` is working as expected, both with your patch or by setting the parameter in the config file. While redirected properly, I am not authenticated the first time I submit to the login action. Using FB, for example: I am redirected to Facebook, approve the app, and then am redirected back. At this point, checking the database shows that a new user has not been created.

At this point DebugKit looks like this:

![first-attempt-session-data](https://cloud.githubusercontent.com/assets/1934719/6016564/0e3bf458-ab41-11e4-8e79-f8293f749ea4.PNG)

![first-attempt-var-data](https://cloud.githubusercontent.com/assets/1934719/6016568/16962a92-ab41-11e4-8e77-6aed91246c0e.PNG)

I am redirected to:

`http://mysite.local/hybrid_auth/hybrid_auth/endpoint?hauth.done=Facebook&code=AQAnFBoxzy2HTo-VH_XgsxluqZRudQGWZjO1xIAgUD4geO-dEN7HiSX6EZccXPmmGxWnqr7-r08F63B1TMeL2t3kVSrZQvfm1k8PCM8YFMvVwjVtt9cVa0uma_xqURiSRXh_kpRAhJpkggn9jA4hDj-pcRXSOCHoCe0KyV8ncNqeKgf4iWKpYk_-BiHunjHwzvuKY1xv9qqydsLtvHdYh3uXdOR5se9gKMmWNyPNXM_biAsJBI3PLOHocFQ3ynPRjYdNb28JRh8PBs0hKFHAJdyMm8fc0r96ohXrtG0HNLxfoH87kd5r-zwgUQLBHAUFDfDYmsNQSFEu1q_XeebqgOKn&state=59c4538c1830cc636b47442345ef3b19#_=_`

Now, if I backtrack and attempt to authenticate a second time around, a new user *is* created and I am logged in. DebutKit now looks like this:

![logged-in](https://cloud.githubusercontent.com/assets/1934719/6016626/f13a3792-ab41-11e4-81f0-83e17609c468.PNG)

One more thing to add, this happens when logging in either a new user or an existing user (who has previously approved the app and is already in the database). The first time attempting to login I do not see any HybridAuth session data and am not auth'd into the app. Yet, in both cases pressing the browser's back button and resubmitting the login action does the trick.

I am using HybridAuth 2.3.* and CakePHP 2.6.*. I experience the same thing locally and pushed to Heroku.

**Comment by ADmad** [comment]
I tested using the openid provider and I was logged in the first time itself and was properly redirect to auth's redirect url after successful login.

Try this, after submitting the form the first time and being redirect to provider, without authorizing open your site in another tab and check the session value. Is `hauth_return_to` set to proper url that you should be redirected to after login?

**Comment by chrisvogt** [comment]
Hi, I have just completed these steps:

* Log in as a test user with provider. This is a new user, who has not yet approved the app and is not in the Users table.

DebugKit looks like:

![01 - start](https://cloud.githubusercontent.com/assets/1934719/6028560/c29131b4-aba7-11e4-99c1-bf37d523b3e5.PNG)

* Attempt to login. Redirected to Facebook for approval.

* Stop here, open a new tab and return to the `users/login` view.

Here DebugKit looks like:

![02 - during](https://cloud.githubusercontent.com/assets/1934719/6028583/ee5bd5b0-aba7-11e4-98c0-c819bf4c6ebb.PNG)

* Close this new tab and return to the first. Approve app on Facebook. Redirected to correct `return_to` point, but not logged in. (Note: redirect view isn't restricted and can be accessed with or w/o auth.)

DebugKit looks like:

![03 - after](https://cloud.githubusercontent.com/assets/1934719/6028602/124b0aea-aba8-11e4-97d2-055913972adb.PNG)

---

Do you see the `Username or password is incorrect` error in DebugKit at 2 & 3 above? Does that tell us anything?

One final thing, if I go back to the login view after all of this, and resubmit again, then a new user is created and I am logged in as them.

**Comment by ADmad** [comment]
Find out who's adding the `messages` to session. It's not cake core, it adds flash messages under `Messsage` key.  Also the second screenshot shows `hauth_session.facebook.is_logged_in` in so HybridAuth has done it's job. If authentication info is available in hauth when you try to access a protected page either the user with matching credentials from db should be returned or registrationcallback should be called or user info provided by hauth should be returned.  So try stepping through HybridAuthAuthenticate::getUser() and figure out what's going wrong.

**Comment by chrisvogt** [comment]
Thank you. I will come back to this in the next 12 hours and let you know if I uncover anything or have more questions.

**Comment by chrisvogt** [comment]
It it taking me longer than anticipated to get xdebug up and running on my vagrant box. I will come back and update this when I do, but here is what I have found in case anyone looks at this and wonders whatever happened.

I have noticed, debugging through trial, that something seemingly unexpected is happening in the `authenticate()` function in `HybridAuthAuthenticate.php` - the first go around the function never reaches the end.

```php
  $this->_init();
  $adapter = $this->hybridAuth->authenticate($provider, $params);
```

Instead, a redirect is being issued under `$this->hybridAuth->authenticate()` the first time it is run.

I assume that isn't intended to happen, since the function ends like so:

```php
  if ($adapter) {
    return $this->_getUser($provider, $adapter);
  }
  return false;
```

However those lines are only reached the second time around.

I'll keep you posted.

**Comment by ADmad** [comment]
> Instead, a redirect is being issued under $this->hybridAuth->authenticate() the first time it is run.

When you submit the login form the redirect to provider when calling `$this->hybridAuth->authenticate()` is expected. I don't think the `if ($adapter) {` is ever reached.

**Comment by chrisvogt** [comment]
I believe I saw it being reached the second time around, but that would make sense because it no longer needs the redirect to the provider. I wonder if something is happening at the endpoint, or if the correct endpoint is even being reached.

**Comment by chrisvogt** [comment]
Haven't updated this in a while. Taking a fresh look at it, I wonder if this might be an issue with Auth config and permissions.

I have set allow on the following actions:

   ```php $this->Auth->allow('index','view', 'public_view', 'display'); ```

Though I haven't included the endpoint in there. Also, if I instead pass a wildcard (*) to allow my results change - while not logged in, my user then populates the views and seems to be stored somewhere on the first time.

Might I need to grant access to `endpoint` or `hybrid_auth/endpoint` if using Auth?

**Comment by ADmad** [comment]
This is an authenticate class you it needs Auth, there's no "if using Auth" :)  Anyway the `endpoint` method is already [allowed](https://github.com/ADmad/CakePHP-HybridAuth/blob/master/Controller/HybridAuthController.php#L32).

**Comment by chrisvogt** [comment]
Here I was ready to stand up and do a victory jump while pouring tears of joy.

I find it odd I don't make it past [here](https://github.com/ADmad/CakePHP-HybridAuth/blob/master/Controller/Component/Auth/HybridAuthAuthenticate.php#L109) the first time around. By the end of [_init()](https://github.com/ADmad/CakePHP-HybridAuth/blob/master/Controller/Component/Auth/HybridAuthAuthenticate.php#L147) `$this->hybridAuth` has an empty `Hybrid_Auth` object. 

The next thing that comes to mind might be sessions. I'm successfully authenticated the second time around, and the difference I notice first is that this second time I hit the `login()` action I already have an hauth session started.

**Comment by ADmad** [comment]
You can add a check in your login() action to see if user is already logged in using Auth->user() and redirect.

**Comment by chrisvogt** [comment]
Ah, that gets me somewhere. Thank you!

It feels like a band-aid, but can log users in if I change the condition in my login action by wrapping my call to `$this->Auth->login()` with the conditions `($this->request->is('post') || $this->Session->read('HA::STORE'))`. While I'm still redirected after the first login attempt, on the redirect action I've added:

        if ($this->Session->read('HA::STORE') && !$this->Auth->user()) {
                $this->redirect('/login');
        }

**Comment by ADmad** [comment]
This means the login works fine the first time itself, problem is only with redirection. After logging in instead of being redirect to url given by Auth->redirectUrl() you are being redirected back to login page. But in the screenshot you have provided earlier i see that value of session key `hauth_return_to` is `/Groups`  so you should be redirected to that url after login.
