### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by urionlinejudge** [ADmad/CakePHP-HybridAuth#91]
Does HybridAuth respect scopes? Like the active field on the normal sign in method? I ask this because it seems to be ignoring that. Thus users that are not active (those that were deactivated) are still able to sign in via social account.

**Comment by ADmad** [comment]
You can use custom finder by using `finder` option in Hybridauth config, which will allow you to modify the query used to find matching user record from db. Check the CakePHP manual for details about using custom finder for authenticators.

**Comment by BassemN** [comment]
@ADmad I did it but if the user can't login because he is not active or blocked, the SQL Log still contains the user find query even the user didn't try to login again as you can see in this [image](https://imgur.com/272pcy5) sorry if I'm not clear enough.

**Comment by BassemN** [comment]
@ADmad What do you think about this issue, please?

**Comment by ADmad** [comment]
I don't understand what your issue is. Your screenshot shows the social profiles table being queried not users table. The social profiles table will always be queried but is corresponding users table record is not enabled and your custom finder sets conditions accordingly then user won't be logged in.

**Comment by BassemN** [comment]
@ADmad Thank you
